#!/bin/sh

while true; do
    if ! updates_arch=$(checkupdates 2> /dev/null | wc -l ); then
        updates_arch=0
    fi

    if ! updates_aur=$(yay -Qum 2> /dev/null | wc -l); then
        updates_aur=0
    fi

    updates=$((updates_arch + updates_aur))

    if [ "$updates" -gt 0 ]; then
        if [ "$updates" -eq 1 ]; then
            echo " $updates update available!"; sleep 30
        else
            echo " $updates updates available!"; sleep 30
        fi
    else
        echo " No updates available."; sleep 1800
    fi
done
