#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
SCRIPTPATH/down

if [ -x "$(command -v feh)" ]; then
    feh --bg-scale "$SCRIPTPATH"/background* &
fi

if [ -x "$(command -v polybar)" ]; then
    "$SCRIPTPATH"/polybar/launch.sh &
fi
